language: python
python:
  - "2.7_with_system_site_packages"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install python-gi python3-gi"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7_with_system_site_packages' ]]; then pip install "twisted==16.6.0"; fi
  - "pip install setuptools twisted tornado"
script:
  - "DEPS=\"$TRAVIS_PYTHON_VERSION `python bin/deps.py`\"; echo $DEPS"
  - "[ \"$DEPS\" == '2.7_with_system_site_packages pygobject tornado twisted' -o
       \"$DEPS\" == '3.3 tornado twisted' -o
       \"$DEPS\" == '3.4 tornado twisted' -o
       \"$DEPS\" == '3.5 tornado twisted' -o
       \"$DEPS\" == '3.6 tornado twisted' -o
       \"$DEPS\" == 'pypy tornado twisted' ]"
  - "python setup.py test"
